# Generated by Django 3.2.7 on 2022-04-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_linkedin',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_phone',
        ),
    ]
