# Generated by Django 3.2.7 on 2022-04-23 09:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_job_application_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_linkedin',
            field=models.URLField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_website',
            field=models.URLField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='link_to_job',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
