# Generated by Django 3.2.7 on 2022-04-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220423_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
    ]
