# Generated by Django 3.2.7 on 2022-04-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_location',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(default='Full Time', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_range',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
